### PR TITLE
fix: privider gitlab get pr comment

### PR DESCRIPTION
**Pull request by wowq**
the gitlab api need repository should include group info ,like `group/project`, not `project`.
But maybe we should test the impact for other git providers

### CODE REVIEW

**Comment by ankitm123** [comment]
o.Repository should now include the subgroup with the repo for nested gitlab repo, can u test and let me know, if we still require this patch?

**Comment by wowq** [comment]
I use the latest version of jx gitops, but I still can't get the correct comment。o.Repository still returns only repo name.，group name not included。 In my use case, only group/project, not org/ group/project

**Comment by ankitm123** [comment]
I have to check, but if the repository was imported using `--nested-repo` flag (jx project import .... --nested-repo), it should work, I will take a look again.

**Comment by babadofar** [comment]
Seeing this on github now

**Comment by ankitm123** [comment]
Needs to be rebased with latest master.

**Comment by babadofar** [comment]
Remade this PR here https://github.com/jenkins-x-plugins/jx-gitops/pull/851

**Comment by babadofar** [comment]
Should be closed

**Pull request closed without merging**
