### PR TITLE
feat: Add support for kustomize

### PR DESCRIPTION
**Pull request by msvticket**
Fixes jenkins-x/jx#8003

### CODE REVIEW

**Comment by msvticket** [comment]
Or maybe it's better to just install kustomize directly in the Dockerfile for the jx-boot image. That would be https://github.com/jenkins-x/jx/blob/main/Dockerfile-boot, right?

**Comment by ankitm123** [comment]
> Or maybe it's better to just install kustomize directly in the Dockerfile for the jx-boot image. That would be https://github.com/jenkins-x/jx/blob/main/Dockerfile-boot, right?

Yes, that's the right dockerfile, but I think it's fine here, probably dont want to add more things to that docker image (it does not include kpt and kubectl, right?)

**Comment by msvticket** [comment]
> > Or maybe it's better to just install kustomize directly in the Dockerfile for the jx-boot image. That would be https://github.com/jenkins-x/jx/blob/main/Dockerfile-boot, right?
> 
> Yes, that's the right dockerfile, but I think it's fine here, probably dont want to add more things to that docker image (it does not include kpt and kubectl, right?)

The plugins installed by  `jx gitops plugin upgrade` are in the jx-boot image. So kubectl is there while kpt is not. So this pull request would make kustomize included in jx-boot, which is the intention. 

I think kustomize should be included in the image for a couple of reasons: 

- https://github.com/jenkins-x/jx3-versions/blob/master/src/Makefile.mk is explicitly customizable to use kustomize
- helmfile is central to jx3 and has integrations with kustomize that you would expect to work

**Pull request merged**
