### PR TITLE
chore: use go 1.22

### PR DESCRIPTION
**Pull request by JordanGoasdoue**
related to https://github.com/jenkins-x/jx/pull/8663

### CODE REVIEW

**Comment by msvticket** [comment]
@JordanGoasdoue Well, that unfortunately failed. You can see the result of CodeQL / Analyze (go) (pull_request)  yourself.

**Comment by JordanGoasdoue** [comment]
indeed @msvticket I was looking about it

seems to be fixed with [this commit](https://github.com/jenkins-x-plugins/jx-gitops/pull/961/commits/c5e73bda691b15202b3ef1d1d80e99c22a592b39)

Now let see if everything is :white_check_mark: :crossed_fingers:

**Review by msvticket — APPROVED** [review]
Let's hope this does the trick

**Pull request merged**
