### PR TITLE
fix: Regen on new cluster

### PR DESCRIPTION
**Pull request by msvticket**
Fixes jenkins-x/jx3-versions#2731

I also added NEW_CLUSTER variable for regen targets which will be useful for jenkins-x/jx3-versions#3223

### CODE REVIEW

**Review by babadofar — COMMENTED** [review]
This most certainly looks good to me!

**Review by tomhobson — APPROVED** [review]

**Comment by tomhobson** [comment]
Great stuff

**Comment by msvticket** [comment]
> Great stuff

I'm not so sure myself anymore. As mentioned in jenkins-x/jx3-versions#3256 you might not have the jenkins.io CRDs in a remote cluster. But I don't know what else to check in the cluster.

**Comment by joshuasimon-taulia** [comment]
@msvticket i see a chore: regenerated commit happening every 5 minutes in my prod remote cluster. is `NEW_CLUSTER 
`jx admin log` shows 
```
/pipeline cancel
no commits so skipping regen-phase-2
make regen-phase-3 NEW_CLUSTER=true
```

where exactly is `NEW_CLUSTER=true` being set? i don't see anything in my makefile
```
jenkins-x-prod-cluster git:(main) grep -Ri NEW_CLUSTER . || echo '0 matches'
0 matches
```

https://kubernetes.slack.com/archives/C9MBGQJRH/p1662085310535669

**Comment by msvticket** [comment]
Just add the Jenkins-X CRDs to the cluster and you should be fine

**Comment by joshuasimon-taulia** [comment]
are any of these CRDs actually used in remote clusters?
```
k get crd | grep -i jenkins
environments.jenkins.io                               2021-08-24T08:43:13Z
lighthousebreakpoints.lighthouse.jenkins.io           2021-08-24T08:43:17Z
lighthousejobs.lighthouse.jenkins.io                  2021-08-24T08:43:17Z
pipelineactivities.jenkins.io                         2021-08-24T08:43:15Z
previews.preview.jenkins.io                           2021-08-24T08:43:17Z
releases.jenkins.io                                   2021-08-24T08:43:15Z
sourcerepositories.jenkins.io                         2021-08-24T08:43:16Z
```

**Comment by joshuasimon-taulia** [comment]
https://github.com/jx3-gitops-repositories/jx3-kubernetes-production doesn't include the `jxgh/jenkins-x-crds` chart

**Comment by msvticket** [comment]
> https://github.com/jx3-gitops-repositories/jx3-kubernetes-production doesn't include the `jxgh/jenkins-x-crds` chart

Yeah, should add it there.

**Pull request merged**
