### PR TITLE
fix: helm release support for OCI registry

### PR DESCRIPTION
**Pull request by babadofar**
solves https://github.com/jenkins-x/jx/issues/8306 
and https://github.com/jenkins-x/jx/issues/8285
but perhaps not https://github.com/jenkins-x/jx/issues/8069

### CODE REVIEW

**Comment by babadofar** [comment]
Sonarcloud fails due to some duplication in the test code. WDYT acceptable or not?

**Review by tomhobson — APPROVED** [review]
Fine with the duplication, makes the tests read way better

**Pull request merged**
