### PR TITLE
Revert "Support for having LighthouseJobs and Tekton jobs in multiple namespaces"

### PR DESCRIPTION
**Pull request by keskad**
Reverts jenkins-x-plugins/jx-gitops#835

Side effect: `kind: Namespace` resources are appearing and are in some corner cases pruned by `kubectl apply --prune`

Will need to prepare a fix to this before we will merge this back.

### CODE REVIEW

**Comment by nicolaerosia** [comment]
OH NO :(

**Comment by keskad** [comment]
@nicolaerosia I feel the same, heh. Don't worry, I will figure out within few days how to proceed with it.

**Pull request merged**
