### PR TITLE
fix: Resources for release build

### PR DESCRIPTION
**Pull request by msvticket**
Trying to fix that goreleaser times out

### CODE REVIEW

**Comment by ankitm123** [comment]
What changed? Seems like the builds are 2x slower 🤔

**Comment by msvticket** [comment]
> What changed? Seems like the builds are 2x slower 🤔

The problem is that my previous attempt made the request of the pod too large so the build stayed pending.
https://dashboard-jx.infra.jenkins-x.rocks/ns-jx/jenkins-x-plugins/jx-gitops/main/25

So I reverted that with https://github.com/jenkins-x-plugins/jx-gitops/pull/862

So I believe this PR and/or jenkins-x/jx3-pipeline-catalog#1128 is needed to fix the time outs. I'll wait and see if merging the other PR is enough and revive this one if not.

**Comment by ankitm123** [comment]
> But my guess is that it has to do with the upgrade of tekton and the changes made to accommodate that

Not sure about that. The only pipeline that slowed down is the go releaser step (almost 2X), the other pipelines are taking almost the same time (including jx3-version)

**Comment by ankitm123** [comment]
Well, lint job for gitops repo is all timing out, might be what you say - tekton upgrade, let me check what is happening with other repos ...

**Pull request closed without merging**
