### PR TITLE
feat: Install/upgrade helm-s3 plugin

### PR DESCRIPTION
**Pull request by msvticket**
Continuing from the previous PR (#806) this PR adds the functionality to install the helm-s3 plugin

### CODE REVIEW

**Comment by ankitm123** [comment]
may want to run `make lint` to see that you dont have linting issues?

**Comment by msvticket** [comment]
If you mean `make lint`I can't really do, that since it is malconfigured:

```
make lint
./hack/gofmt.sh
./hack/linter.sh
INFO [config_reader] Config search paths: [./ /Users/msv/Documents/projects/jx-gitops /Users/msv/Documents/projects /Users/msv/Documents /Users/msv /Users /]
INFO [config_reader] Used config file .golangci.yml
WARN Gocritic check "dupImport" was disabled by config, was it's not enabled, no need to disable it
WARN Gocritic check "whyNoLint" was disabled by config, was it's not enabled, no need to disable it
ERRO Invalid gocritic settings: validation failed: disabled checker dupImport doesn't exist, all existing checkers: [appendassign appendcombine argorder assignop badcond boolexprsimplify builtinshadow captlocal caseorder codegencomment commentedoutcode commentedoutimport commentformatting defaultcaseorder deprecatedcomment docstub duparg dupbranchbody dupcase dupsubexpr elseif emptyfallthrough emptystringtest equalfold exitafterdefer flagderef flagname hexliteral hugeparam ifelsechain importshadow indexalloc initclause methodexprcall nestingreduce nilvalreturn octalliteral offby1 paramtypecombine ptrtorefparam rangeexprcopy rangevalcopy regexpmust singlecaseswitch sloppylen sloppyreassign stringxbytes switchtrue typeassertchain typeswitchvar typeunparen underef unlabelstmt unlambda unnamedresult unnecessaryblock unslice valswap weakcond wrapperfunc yodastyleexpr]
make: *** [lint] Error 3
```

**Comment by ankitm123** [comment]
What version of golang ci lint are u using? It works for me :confused:

**Comment by msvticket** [comment]
1.16.0

**Comment by ankitm123** [comment]
> 1.16.0

Can u upgrade it to 1.42.1? That should work ...

**Comment by ankitm123** [comment]
I personally prefer:  `docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.42.1 golangci-lint run -v`, as it does not mess up with local versions of golang-ci lint, but :shrug:

**Comment by ankitm123** [comment]
the sonarcloud failure can be overridden as those are false positives ...

**Pull request merged**
